### ISSUE TITLE
lacks of join event

### ISSUE THREAD

**Issue by chsqn** [colyseus/colyseus-defold#23]
It seems like [room](https://github.com/colyseus/colyseus-defold/blob/dc7b331c70c7675df9a10403ac0ff7c050a9116b/colyseus/room.lua#L48) lacks of join event.
```
function Room:connect (endpoint)
  self.connection:on("open", function()
     self:emit("join")
  end)

  self.connection:on("message", function(message)
    self:on_batch_message(message)
  end)
```

**Comment by endel** [comment]
Hi @chsqn, the matchmaking methods are part of the `client`:
https://github.com/colyseus/colyseus-defold/blob/dc7b331c70c7675df9a10403ac0ff7c050a9116b/colyseus/client.lua#L58-L76

**Comment by chsqn** [comment]
The callback will call back at here:
https://github.com/colyseus/colyseus-defold/blob/dc7b331c70c7675df9a10403ac0ff7c050a9116b/colyseus/client.lua#L58-L60
https://github.com/colyseus/colyseus-defold/blob/dc7b331c70c7675df9a10403ac0ff7c050a9116b/colyseus/client.lua#L106-L109
https://github.com/colyseus/colyseus-defold/blob/dc7b331c70c7675df9a10403ac0ff7c050a9116b/colyseus/client.lua#L112
But join events don't emit at here:
https://github.com/colyseus/colyseus-defold/blob/dc7b331c70c7675df9a10403ac0ff7c050a9116b/colyseus/room.lua#L48-L63

**Comment by endel** [comment]
Hi @chsqn, I see what the question is about now. The `"join"` event is not supposed to be used anymore by you on version `0.11`. When the callback is triggered returning the room instance, it means that it has been joined successfully.

See the example: https://github.com/colyseus/colyseus-defold/blob/dc7b331c70c7675df9a10403ac0ff7c050a9116b/example/example.script#L32-L42

If there are no errors (line 34), you can already call the methods of the room, because it was joined successfully.

**Comment by chsqn** [comment]
You are right. The join event will be emitted at here.
https://github.com/colyseus/colyseus-defold/blob/751dc2c87319df4b631a510bc0f4b5452630ebbe/colyseus/room.lua#L123

**Comment by endel** [comment]
Cool, closing this, feel free to re-open if you have any questions!
